### ISSUE TITLE
Handle incorrect gltf parsing by renaming to glb and then back

### ISSUE THREAD

**Issue by fire** [xpportal/omi-personality-transform-script#3]
Handle incorrect gltf parsing by renaming to glb and then back.

1. Input example.vrm
2. Rename to example.glb
3. Process with gltf-transform
4. Rename back to example.vrm

## Security note

Probably want the temporary file to be un-guessable. See stories of php security tmp file guessing.

**Comment by antpb** [comment]
Done in: https://github.com/xpportal/omi-personality-transform-script/pull/6
